#!/usr/bin/env python3
"""
Type 3: Instruction Following (IF) dialogue generation.
Generates multi-turn dialogues where 甲 gives 3-6 IF tasks and 乙 executes them.
14 task types aligned with spoken-language-model evaluation set.

Task content (instructions + answers) is generated by the main LLM at runtime
using few-shot examples — no large static lists required.

Usage:
    python generate/gen_if_data.py --config conf/if_data.yaml \
        --num-dialogues 1600 --output output/if_data/
"""
import argparse
import json
import logging
import random
import re
import sys
import time
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).parent.parent))
from generate.base_generator import VLLMClient, extract_json, contains_english, fix_simplified
from generate.gen_user_agent import load_config

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

# ── 題型定義 ────────────────────────────────────────────────────────────────

# 14 種題型及其比例權重（對齊推論集分布：朗讀/列舉/數數/序列佔大宗）
QTYPE_WEIGHTS = {
    "朗讀":   8,   # 朗讀指定句子（推論集最核心）
    "列舉":   4,   # 說出 N 種某類事物
    "數數":   3,   # 從 M 數到 N
    "倒數":   3,   # 從 N 倒數到 M
    "序列":   3,   # 說出固定序列（星期/月份/四季等）
    "複述":   3,   # 把句子重複一遍（措辭不同於朗讀）
    "描述":   3,   # 場景/事物短篇描述
    "感受描述": 2,  # 描述某種感官或情緒感受
    "比較":   2,   # 比較兩樣事物哪個更...
    "舉例":   2,   # 舉一個某類事物的例子
    "說出喜好": 2,  # 說出最喜歡/不喜歡的事物
    "問答":   3,   # 回答知識型問題
    "反義詞":  1,
    "同義詞":  1,
}

QTYPES = list(QTYPE_WEIGHTS.keys())
QTYPE_WEIGHT_LIST = [QTYPE_WEIGHTS[k] for k in QTYPES]

# ── LLM 動態題型（few-shot 範例）─────────────────────────────────────────────

# 每種題型 2~3 個範例；LLM 用這些範例生成新的、多元的題目和答案
TASK_EXAMPLES = {
    "朗讀": [
        ("請說這句話，知識就是力量。", "知識就是力量。"),
        ("請朗讀這句，海浪一波一波地打上沙灘。", "海浪一波一波地打上沙灘。"),
        ("念一遍，失敗是成功之母。", "失敗是成功之母。"),
    ],
    "複述": [
        ("把這句話說一遍，一分耕耘，一分收穫。", "一分耕耘，一分收穫。"),
        ("跟著說，天下無難事，只怕有心人。", "天下無難事，只怕有心人。"),
        ("重複這句話，春天到了，萬物都開始甦醒。", "春天到了，萬物都開始甦醒。"),
    ],
    "數數": [
        ("請從一數到六", "一、二、三、四、五、六"),
        ("從三數到十", "三、四、五、六、七、八、九、十"),
        ("幫我從五數到十二", "五、六、七、八、九、十、十一、十二"),
    ],
    "倒數": [
        ("請從八倒數到一", "八、七、六、五、四、三、二、一"),
        ("從十倒數到五", "十、九、八、七、六、五"),
        ("倒著數，從十五到十", "十五、十四、十三、十二、十一、十"),
    ],
    "列舉": [
        ("請說出三種台灣著名的夜市小吃", None),
        ("說出四種常見的交通工具", None),
        ("列舉三種台灣的節日", None),
    ],
    "序列": [
        ("請說出一週七天", "星期一、星期二、星期三、星期四、星期五、星期六、星期日"),
        ("依序說出四季", "春天、夏天、秋天、冬天"),
        ("請把一月到六月念出來", "一月、二月、三月、四月、五月、六月"),
    ],
    "描述": [
        ("請用一兩句話描述夏天的感覺", None),
        ("用一兩句話描述熱鬧的夜市", None),
        ("描述一個下雨天的早晨", None),
    ],
    "感受描述": [
        ("描述踩進泥巴裡的感覺", None),
        ("說說看在黑暗森林中迷路是什麼感受", None),
        ("描述吃到酸梅時的味覺感受", None),
    ],
    "比較": [
        ("你覺得貓和狗哪個比較好養？為什麼？", None),
        ("夏天和冬天你比較喜歡哪個？", None),
        ("走路和騎腳踏車，哪個比較環保？", None),
    ],
    "舉例": [
        ("請舉一個台灣傳統節日的例子", None),
        ("舉一個日常生活中環保行為的例子", None),
        ("說一個你覺得有益健康的運動例子", None),
    ],
    "說出喜好": [
        ("你最喜歡的水果是什麼？", None),
        ("說出你最不喜歡的一種天氣", None),
        ("你最喜歡哪個季節？", None),
    ],
    "問答": [
        ("台灣的首都是哪裡？", "台北"),
        ("一年有幾個月？", "十二個月"),
        ("彩虹有幾種顏色？", "七種"),
    ],
    "反義詞": [
        ("「快樂」的反義詞是什麼？", "悲傷"),
        ("「勤勞」的反義詞？", "懶惰"),
        ("說出「明亮」的反義詞", "黑暗"),
    ],
    "同義詞": [
        ("請說一個「漂亮」的同義詞", "美麗"),
        ("「高興」的同義詞？", "開心"),
        ("說個「努力」的同義詞", "用功"),
    ],
}


def gen_tasks_for_dialogue(client, qtypes: list[str]) -> list[dict]:
    """
    Call LLM once to generate fresh, diverse task instructions + answers for all qtypes.
    Returns list of dicts: {instruction, answer} (answer=None for open-ended tasks).
    """
    n = len(qtypes)

    # Build few-shot block (unique types only)
    seen: set[str] = set()
    few_shot_lines = []
    for qt in qtypes:
        if qt in seen:
            continue
        seen.add(qt)
        exs = TASK_EXAMPLES.get(qt, [])
        if exs:
            few_shot_lines.append(f"【{qt}】")
            for inst, ans in exs:
                ans_str = ans if ans else "（開放式）"
                few_shot_lines.append(f"  指令：{inst}  答案：{ans_str}")

    qtype_seq = "、".join(qtypes)
    few_shot_block = "\n".join(few_shot_lines)

    prompt = f"""請依序生成 {n} 個語言指令任務，題型序列：{qtype_seq}

各題型範例（照格式但不要抄，要多元新鮮）：
{few_shot_block}

規則：
- 每題指令口語、簡潔，不超過三十個字
- 標點只能用：，。？！、：
- 語言：繁體中文台灣腔，禁止英文字母、阿拉伯數字
- 有固定答案的題型（朗讀、複述、數數、倒數、序列、反義詞、同義詞、問答）必須提供正確 answer
- 朗讀、複述的句子長短要多元：五到二十一個字，對齊推論集分布
- 數數、倒數的 answer 用頓號分隔每個數字，最多十三個數字
- 描述、感受描述、比較、舉例、列舉、說出喜好 → answer 填 null
- 同一段對話中題目內容要多元，不要重複一樣的句子或主題

輸出純 JSON 陣列（長度 {n}）：
[{{"type": "朗讀", "instruction": "...", "answer": "..."}}, ...]"""

    for attempt in range(3):
        try:
            raw = client.chat(
                [{"role": "user", "content": prompt}],
                temperature=0.9, top_p=0.95, max_tokens=1500,
            )
            data = extract_json(raw)
            if isinstance(data, list) and len(data) >= n - 1:
                results = []
                for j in range(n):
                    item = data[j] if j < len(data) else {}
                    results.append({
                        "instruction": fix_simplified(str(item.get("instruction", "請說一句話"))),
                        "answer": item.get("answer"),
                    })
                return results
        except Exception as e:
            logger.warning(f"Task gen failed (attempt {attempt+1}): {e}")
        time.sleep(1)

    # Fallback: minimal static templates
    fallback_map = {
        "朗讀": ("請說這句話，失敗是成功之母。", "失敗是成功之母。"),
        "複述": ("重複這句話，知識就是力量。", "知識就是力量。"),
        "數數": ("請從一數到八", "一、二、三、四、五、六、七、八"),
        "倒數": ("請從八倒數到一", "八、七、六、五、四、三、二、一"),
        "列舉": ("說出三種常見的水果", None),
        "序列": ("說出一週七天", "星期一、星期二、星期三、星期四、星期五、星期六、星期日"),
        "描述": ("描述夏天的感覺", None),
        "說出喜好": ("你最喜歡的水果是什麼？", None),
        "問答": ("台灣的首都是哪裡？", "台北"),
        "反義詞": ("「快樂」的反義詞是什麼？", "悲傷"),
        "同義詞": ("「漂亮」的同義詞？", "美麗"),
    }
    return [
        {"instruction": fallback_map.get(qt, ("請說一句話", None))[0],
         "answer": fallback_map.get(qt, ("請說一句話", None))[1]}
        for qt in qtypes
    ]


# ── 過渡語助詞（偶爾插在非首輪 instructor 前） ────────────────────────────────
_TRANSITIONS = ["對了，", "接著，", "那，", "再來，", "好，那下一題，"]


def _inject_transitions(turns: list[dict]) -> list[dict]:
    """With ~25% probability, prepend a transition phrase to non-first User turns."""
    user_count = 0
    result = []
    for t in turns:
        if t["role"] == "User":
            user_count += 1
            if user_count > 1 and random.random() < 0.25:
                prefix = random.choice(_TRANSITIONS)
                result.append({**t, "text": prefix + t["text"]})
                continue
        result.append(t)
    return result


# ── System prompt 生成 ───────────────────────────────────────────────────────

_SYSTEM_PROMPT_CONTEXTS = [
    "課堂練習", "語言挑戰遊戲", "口語練習",
    "語言測驗", "互動練習", "腦力訓練",
]

def gen_system_prompt_if(client, qtypes: list[str]) -> str:
    context = random.choice(_SYSTEM_PROMPT_CONTEXTS)
    prompt = (
        f"根據以下情境，寫一到兩句話的系統提示詞（二十到四十個字），說明甲乙兩人正在進行的活動。\n\n"
        f"情境：甲和乙正在進行{context}，甲依序提出語言指令（包括：{'、'.join(qtypes[:3])}等），乙精準執行每一題。\n\n"
        f"規定：\n"
        f"- 只輸出提示詞本身，不要說明或引號。\n"
        f"- 繁體中文台灣用語，不可出現英文。\n"
        f"- 不要提到甲乙的名字，用「兩人」或「他們」。\n"
        f"- 自然描述即可，不要太正式。"
    )
    for attempt in range(3):
        try:
            raw = client.chat(
                [{"role": "user", "content": prompt}],
                temperature=0.7,
                top_p=0.9,
                max_tokens=80,
            )
            result = fix_simplified(raw.strip().splitlines()[0])
            if result and not contains_english(result):
                return result
        except Exception:
            pass
    return f"兩人正在進行語言{context}，依序完成各種語言指令任務。"


# ── 對話生成 ─────────────────────────────────────────────────────────────────

def _build_prompt(tasks: list[dict], num_turns: int) -> str:
    task_lines = []
    for i, t in enumerate(tasks, 1):
        ans_hint = f"（標準答案：{t['answer']}）" if t.get("answer") else ""
        task_lines.append(f"{i}. 甲：{t['instruction']}{ans_hint}")
    task_block = "\n".join(task_lines)

    return f"""生成一段對話，甲依序給出以下 {len(tasks)} 個指令，乙精準執行。

指令清單：
{task_block}

規則：
- 語言：繁體中文台灣用語，不可出現英文字母或阿拉伯數字，數字用中文。
- 標點符號只能用：，。？！、：（禁止引號、書名號、括號、分號、破折號、省略號）
- 甲照指令清單給指令，措辭可微調但意思不變。
- 有標準答案的題型乙必須答對。
- 乙的回答直接、簡潔：列舉多項時用頓號分隔，回答完整句子結尾加句號。
- 每輪最多六十個字。
- 禁止：Markdown、條列符號、括號說明、旁白。

輸出格式（嚴格遵守）：
- 只輸出對話本文。
- 每行格式：甲：... 或 乙：...
- 禁止空白行，禁止同一回合換行。
- 從甲開始，甲乙交替，共 {num_turns} 行。"""


def gen_if_dialogue(client, cfg: dict, qtypes: list[str]) -> dict:
    """Returns {"system_prompt": str, "turns": list[dict]} or empty dict on failure."""
    tasks = gen_tasks_for_dialogue(client, qtypes)
    tasks = [t for t in tasks if t is not None]
    if not tasks:
        return {}

    num_turns = len(tasks) * 2
    prompt = _build_prompt(tasks, num_turns)
    max_retries = cfg["vllm"]["max_retries"]
    retry_delay = cfg["vllm"]["retry_delay"]

    system_prompt = gen_system_prompt_if(client, qtypes)

    for attempt in range(max_retries):
        try:
            raw = client.chat(
                [{"role": "user", "content": prompt}],
                temperature=cfg["gen"]["temperature"],
                top_p=cfg["gen"]["top_p"],
                max_tokens=cfg["gen"].get("max_tokens", 1024),
            )
            turns = _parse_turns(raw)
            if len(turns) < max(4, num_turns - 2):
                raise ValueError(f"Too few turns: {len(turns)} (expected ~{num_turns})")
            return {"system_prompt": system_prompt, "turns": _inject_transitions(turns)}
        except Exception as e:
            logger.warning(f"IF dialogue gen failed (attempt {attempt+1}): {e}")
            time.sleep(retry_delay)
    return {}


def _parse_turns(raw: str) -> list[dict]:
    turns = []
    role_map = {"甲": "User", "乙": "Agent"}
    for line in raw.splitlines():
        line = line.strip()
        m = re.match(r"^([甲乙])：(.+)$", line)
        if not m:
            continue
        role_zh, text = m.group(1), m.group(2).strip()
        text = fix_simplified(text)
        if contains_english(text) or len(text) < 2:
            continue
        if text and text[-1] not in "。！？…、":
            text += "。"
        turns.append({"role": role_map[role_zh], "text": text})
    return turns


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Generate IF dialogues")
    parser.add_argument("--config", required=True)
    parser.add_argument("--num-dialogues", type=int, default=1600)
    parser.add_argument("--tts-total", type=int, default=None,
                        help="Total dialogue count used to compute 75/25 BreezyVoice/IndexTTS split. "
                             "Defaults to --num-dialogues. Set this when extending an existing dataset.")
    parser.add_argument("--output", required=True)
    parser.add_argument("--vllm-url", default=None)
    parser.add_argument("--worker-id", type=int, default=0)
    parser.add_argument("--num-workers", type=int, default=1)
    args = parser.parse_args()

    cfg = load_config(args.config)
    if args.vllm_url:
        cfg["vllm"]["base_url"] = args.vllm_url

    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_jsonl = out_dir / f"dialogues_w{args.worker_id:02d}.jsonl"

    min_tasks = cfg.get("min_tasks", 3)
    max_tasks = cfg.get("max_tasks", 6)

    client = VLLMClient(
        base_url=cfg["vllm"]["base_url"],
        model=cfg["vllm"]["model"],
        api_key=cfg["vllm"].get("api_key", "token"),
        timeout=cfg["vllm"].get("timeout", 120),
        max_retries=cfg["vllm"].get("max_retries", 5),
        retry_delay=cfg["vllm"].get("retry_delay", 2.0),
    )

    total = args.num_dialogues
    tts_total = args.tts_total if args.tts_total is not None else total
    per_worker = total // args.num_workers
    start = args.worker_id * per_worker
    end = start + per_worker if args.worker_id < args.num_workers - 1 else total

    existing_ids: set[str] = set()
    if out_jsonl.exists():
        with open(out_jsonl) as f:
            for line in f:
                try:
                    existing_ids.add(json.loads(line)["id"])
                except Exception:
                    pass
    logger.info(f"[Worker {args.worker_id}] Range [{start}, {end}), existing={len(existing_ids)}")

    with open(out_jsonl, "a", encoding="utf-8") as fout:
        for idx in range(start, end):
            dialogue_id = f"if_data_{idx:06d}"
            if dialogue_id in existing_ids:
                continue

            num_tasks = random.randint(min_tasks, max_tasks)
            qtypes = random.choices(QTYPES, weights=QTYPE_WEIGHT_LIST, k=num_tasks)
            qtypes = [qtypes[0]] + [q for i, q in enumerate(qtypes[1:]) if q != qtypes[i]]

            backend = "breezyvoice" if idx < int(tts_total * 0.75) else "indextts"

            result = gen_if_dialogue(client, cfg, qtypes)
            if not result:
                logger.warning(f"Empty dialogue for {dialogue_id}, skipping")
                continue

            record = {
                "id": dialogue_id,
                "type": "if_data",
                "tts_backend": backend,
                "if_tasks": qtypes,
                "system_prompt": result["system_prompt"],
                "turns": [{"role": t["role"], "text": t["text"], "speed": "normal"}
                          for t in result["turns"]],
            }
            fout.write(json.dumps(record, ensure_ascii=False) + "\n")
            fout.flush()

            if (idx - start) % 50 == 0:
                logger.info(f"[Worker {args.worker_id}] {idx - start}/{end - start} done")


if __name__ == "__main__":
    main()
